language: python
dist: xenial

matrix:
  include:
    # These are quick and often catch errors, so list them first
    - python: 3.6
      env: CHECK_DOCS=1
    - python: 3.6
      env: CHECK_FORMATTING=1
    - python: pypy2.7-7.1.1
    - python: 2.7
    - python: pypy3.5
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8-dev
    - os: osx
      language: generic
      env: MACPYTHON=3.5.4
    - os: osx
      language: generic
      env: MACPYTHON=3.6.7
    - os: osx
      language: generic
      env: MACPYTHON=3.7.1

script:
  - ci/travis.sh
